// Traditional Bingo Calling Phrases for 75-ball Bingo
// These colorful nicknames add fun and tradition to the game

export const BINGO_CALLS: Record<number, string> = {
  1: "Kelly's Eye",
  2: "One Little Duck",
  3: "Cup of Tea",
  4: "Knock at the Door",
  5: "Man Alive",
  6: "Half a Dozen",
  7: "Lucky Seven",
  8: "Garden Gate",
  9: "Doctor's Orders",
  10: "Downing Street",
  11: "Legs Eleven",
  12: "One Dozen",
  13: "Unlucky for Some",
  14: "Valentine's Day",
  15: "Young and Keen",
  16: "Sweet Sixteen",
  17: "Dancing Queen",
  18: "Coming of Age",
  19: "Goodbye Teens",
  20: "One Score",
  21: "Key of the Door",
  22: "Two Little Ducks",
  23: "Thee and Me",
  24: "Two Dozen",
  25: "Duck and Dive",
  26: "Pick and Mix",
  27: "Gateway to Heaven",
  28: "Overweight",
  29: "Rise and Shine",
  30: "Dirty Gertie",
  31: "Get Up and Run",
  32: "Buckle My Shoe",
  33: "Dirty Knee",
  34: "Ask for More",
  35: "Jump and Jive",
  36: "Three Dozen",
  37: "More than Eleven",
  38: "Christmas Cake",
  39: "Steps",
  40: "Naughty Forty",
  41: "Time for Fun",
  42: "Winnie the Pooh",
  43: "Down on Your Knees",
  44: "All the Fours",
  45: "Halfway There",
  46: "Up to Tricks",
  47: "Four and Seven",
  48: "Four Dozen",
  49: "PC",
  50: "Half a Century",
  51: "Tweak of the Thumb",
  52: "Danny La Rue",
  53: "Stuck in the Tree",
  54: "Clean the Floor",
  55: "All the Fives",
  56: "Was She Worth It?",
  57: "Heinz Varieties",
  58: "Make Them Wait",
  59: "Brighton Line",
  60: "Five Dozen",
  61: "Baker's Bun",
  62: "Turn on the Screw",
  63: "Tickle Me",
  64: "Red Raw",
  65: "Old Age Pension",
  66: "Clickety Click",
  67: "Made in Heaven",
  68: "Saving Grace",
  69: "Either Way Up",
  70: "Three Score and Ten",
  71: "Bang on the Drum",
  72: "Six Dozen",
  73: "Queen B",
  74: "Candy Store",
  75: "Strive and Strive",
};

export function getBingoCall(num: number): string | undefined {
  return BINGO_CALLS[num];
}
